services:
  mediawiki:
    image: mediawiki:latest
    container_name: mediawiki
    ports:
      - "8080:80"
    volumes:
      - mediawiki_data:/var/www/html
      - ./LocalSettings.php:/var/www/html/LocalSettings.php
      - ./initialize_wikipedia.sh:/docker-entrypoint-initdb.d/initialize_wikipedia.sh
    environment:
      - MEDIAWIKI_DB_HOST=db
      - MEDIAWIKI_DB_NAME=mediawiki
      - MEDIAWIKI_DB_USER=mediawiki
      - MEDIAWIKI_DB_PASSWORD=mediawiki_password
    depends_on:
      - db
    command: ["bash", "-c", "/docker-entrypoint-initdb.d/initialize_wikipedia.sh && apache2-foreground"]

  db:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: mediawiki
      MYSQL_USER: mediawiki
      MYSQL_PASSWORD: mediawiki_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root_password

volumes:
  mediawiki_data:
  db_data:
